name: health_analyzer
description: A Flutter app to analyze and track blood report trends over time
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Google Gemini AI
  google_generative_ai: ^0.2.2
  
  # File Picking
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  
  # Charts
  fl_chart: ^0.65.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Date/Time utilities
  intl: ^0.19.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # HTTP Client
  http: ^1.2.0
  
  # Fuzzy Matching
  fuzzywuzzy: ^1.2.0
  
  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
